#   workbooks = {kopanos, general}
#   action_space_types = {discrete, discrete_probs, continuous}
#   rewards = {OCC, MAKESPAN, WL, LENGTH, COMPLETION}
#   obs_sizes = {small, medium, big}
#   products_number = {30, 60}
#   buffer_usages = {no_buffers, always_buffers, random, agent_decides}
#   heuristics = {None, FIFO, EDD, SPT, SCT}
#   solutions = {None, FIFO, EDD, SPT, SCT, kopanos}
#   test = {ppo_optuna, ppo_manual, ppo_test_trained, simple_run}
# config.yaml

params:
  - N_TIMESTEPS: 10
    seed: 0
    masking: True
    reward: OCC
    buffer_usage: no_buffers
    time_in_buffer_custom: 1
    workbook: kopanos
    obs_size: big
    action_space: discrete_probs
    solution_hints: None
    products_number: 30
    generate_heuristic_schedules: FIFO
    recreate_solution: None
    test: ppo_manual